services:
  - type: web
    name: synthreview
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
